// scripts/seed_firestore.js
// Run: node seed_firestore.js

const admin = require('firebase-admin');
const serviceAccount = require('./serviceAccountKey.json');

admin.initializeApp({
  credential: admin.credential.cert(serviceAccount),
});

const db = admin.firestore();

// ── Categories ────────────────────────────────────────────────────────────────
const categories = [
  { id: 'electronics',  name: 'Electronics', name_ar: 'الإلكترونيات', icon: '📱', image_url: 'https://picsum.photos/seed/electronics/400/400',  product_count: 8,  is_active: true },
  { id: 'fashion',      name: 'Fashion',     name_ar: 'الأزياء',       icon: '👗', image_url: 'https://picsum.photos/seed/fashion/400/400',      product_count: 6,  is_active: true },
  { id: 'food',         name: 'Food',        name_ar: 'الطعام',         icon: '🍔', image_url: 'https://picsum.photos/seed/food/400/400',         product_count: 4,  is_active: true },
  { id: 'home',         name: 'Home',        name_ar: 'المنزل',         icon: '🏠', image_url: 'https://picsum.photos/seed/home/400/400',         product_count: 4,  is_active: true },
  { id: 'sports',       name: 'Sports',      name_ar: 'الرياضة',        icon: '⚽', image_url: 'https://picsum.photos/seed/sports/400/400',       product_count: 4,  is_active: true },
  { id: 'beauty',       name: 'Beauty',      name_ar: 'الجمال',         icon: '💄', image_url: 'https://picsum.photos/seed/beauty/400/400',       product_count: 4,  is_active: true },
];

// ── 30 Products ───────────────────────────────────────────────────────────────
const products = [

  // ── Electronics (8 products) ─────────────────────────────────────────────
  {
    name:           'iPhone 15 Pro Max',
    description:    'The most powerful iPhone ever with A17 Pro chip, titanium design, and a 48MP main camera. Featuring ProMotion display with always-on technology and up to 29 hours of video playback.',
    price:          4999,
    discount_price: 4499,
    images:         [
      'https://picsum.photos/seed/iphone15/400/400',
      'https://picsum.photos/seed/iphone15b/400/400',
      'https://picsum.photos/seed/iphone15c/400/400',
    ],
    category_id:    'electronics',
    category_name:  'Electronics',
    brand:          'Apple',
    rating:         4.9,
    review_count:   2340,
    stock:          15,
    tags:           ['phone', 'apple', 'iphone', 'smartphone'],
    is_featured:    true,
    is_new:         true,
    is_active:      true,
    created_at:     admin.firestore.Timestamp.now(),
  },
  {
    name:           'Samsung Galaxy S24 Ultra',
    description:    'Next-generation AI smartphone with built-in S Pen, 200MP camera, and titanium frame. Features Galaxy AI for live translation, chat assist, and circle to search.',
    price:          4499,
    discount_price: null,
    images:         [
      'https://picsum.photos/seed/s24ultra/400/400',
      'https://picsum.photos/seed/s24ultrab/400/400',
    ],
    category_id:    'electronics',
    category_name:  'Electronics',
    brand:          'Samsung',
    rating:         4.8,
    review_count:   1890,
    stock:          22,
    tags:           ['phone', 'samsung', 'android', 'galaxy'],
    is_featured:    true,
    is_new:         true,
    is_active:      true,
    created_at:     admin.firestore.Timestamp.now(),
  },
  {
    name:           'MacBook Pro 14" M3 Pro',
    description:    'Supercharged by M3 Pro chip with 12-core CPU and 18-core GPU. Up to 22 hours of battery life, Liquid Retina XDR display, and up to 36GB unified memory.',
    price:          8999,
    discount_price: 7999,
    images:         [
      'https://picsum.photos/seed/macbookpro/400/400',
      'https://picsum.photos/seed/macbookprob/400/400',
    ],
    category_id:    'electronics',
    category_name:  'Electronics',
    brand:          'Apple',
    rating:         4.9,
    review_count:   760,
    stock:          10,
    tags:           ['laptop', 'apple', 'macbook', 'mac', 'computer'],
    is_featured:    true,
    is_new:         false,
    is_active:      true,
    created_at:     admin.firestore.Timestamp.now(),
  },
  {
    name:           'Sony WH-1000XM5 Headphones',
    description:    'Industry-leading noise canceling with Auto NC Optimizer. 30-hour battery life, multipoint connection, and crystal clear hands-free calling with 8 microphones.',
    price:          1499,
    discount_price: 1199,
    images:         [
      'https://picsum.photos/seed/sonywh/400/400',
      'https://picsum.photos/seed/sonya/400/400',
    ],
    category_id:    'electronics',
    category_name:  'Electronics',
    brand:          'Sony',
    rating:         4.8,
    review_count:   5600,
    stock:          35,
    tags:           ['headphones', 'sony', 'audio', 'wireless', 'noise-canceling'],
    is_featured:    false,
    is_new:         false,
    is_active:      true,
    created_at:     admin.firestore.Timestamp.now(),
  },
  {
    name:           'iPad Pro 12.9" M2',
    description:    'The ultimate iPad experience with M2 chip, ProMotion XDR display, and Apple Pencil hover. Works with Magic Keyboard and Apple Pencil 2nd generation.',
    price:          4299,
    discount_price: 3799,
    images:         [
      'https://picsum.photos/seed/ipadpro/400/400',
      'https://picsum.photos/seed/ipadprob/400/400',
    ],
    category_id:    'electronics',
    category_name:  'Electronics',
    brand:          'Apple',
    rating:         4.7,
    review_count:   1230,
    stock:          18,
    tags:           ['tablet', 'apple', 'ipad', 'ipadpro'],
    is_featured:    true,
    is_new:         false,
    is_active:      true,
    created_at:     admin.firestore.Timestamp.now(),
  },
  {
    name:           'Samsung 65" QLED 4K TV',
    description:    'Quantum Dot technology delivers 100% color volume. Neo QLED with Mini LED for precise contrast. Powered by Neural Quantum Processor 4K with 60+ AI optimizations.',
    price:          5499,
    discount_price: 4299,
    images:         [
      'https://picsum.photos/seed/samsungtv/400/400',
      'https://picsum.photos/seed/samsungtvb/400/400',
    ],
    category_id:    'electronics',
    category_name:  'Electronics',
    brand:          'Samsung',
    rating:         4.6,
    review_count:   890,
    stock:          8,
    tags:           ['tv', 'samsung', 'qled', '4k', 'television'],
    is_featured:    false,
    is_new:         false,
    is_active:      true,
    created_at:     admin.firestore.Timestamp.now(),
  },
  {
    name:           'PlayStation 5 Console',
    description:    'Experience lightning-fast loading with an ultra-high speed SSD, deeper immersion with support for haptic feedback, adaptive triggers, and 3D Audio.',
    price:          2199,
    discount_price: null,
    images:         [
      'https://picsum.photos/seed/ps5/400/400',
      'https://picsum.photos/seed/ps5b/400/400',
    ],
    category_id:    'electronics',
    category_name:  'Electronics',
    brand:          'Sony',
    rating:         4.9,
    review_count:   4500,
    stock:          5,
    tags:           ['gaming', 'sony', 'playstation', 'ps5', 'console'],
    is_featured:    true,
    is_new:         false,
    is_active:      true,
    created_at:     admin.firestore.Timestamp.now(),
  },
  {
    name:           'Apple Watch Series 9',
    description:    'The most powerful Apple Watch yet with the new S9 chip, double tap gesture, and brighter always-on display. Carbon neutral with a new Fine Woven band.',
    price:          1599,
    discount_price: 1399,
    images:         [
      'https://picsum.photos/seed/applewatch/400/400',
      'https://picsum.photos/seed/applewatchb/400/400',
    ],
    category_id:    'electronics',
    category_name:  'Electronics',
    brand:          'Apple',
    rating:         4.7,
    review_count:   2100,
    stock:          28,
    tags:           ['watch', 'apple', 'smartwatch', 'wearable'],
    is_featured:    false,
    is_new:         true,
    is_active:      true,
    created_at:     admin.firestore.Timestamp.now(),
  },

  // ── Fashion (6 products) ──────────────────────────────────────────────────
  {
    name:           'Nike Air Max 270',
    description:    'The Nike Air Max 270 delivers a lifestyle shoe with a large Air unit and a sleek silhouette. The bold design with its 270-degree Max Air unit is the largest Air heel unit yet.',
    price:          649,
    discount_price: 549,
    images:         [
      'https://picsum.photos/seed/airmax/400/400',
      'https://picsum.photos/seed/airmaxb/400/400',
    ],
    category_id:    'fashion',
    category_name:  'Fashion',
    brand:          'Nike',
    rating:         4.6,
    review_count:   3200,
    stock:          45,
    tags:           ['shoes', 'nike', 'airmax', 'sneakers', 'sport'],
    is_featured:    true,
    is_new:         false,
    is_active:      true,
    created_at:     admin.firestore.Timestamp.now(),
  },
  {
    name:           'Adidas Ultraboost 23',
    description:    'Experience incredible energy return with the Boost midsole and a Primeknit+ upper that adapts to your foot. The Linear Energy Push system propels you forward.',
    price:          799,
    discount_price: 699,
    images:         [
      'https://picsum.photos/seed/ultraboost/400/400',
      'https://picsum.photos/seed/ultraboostb/400/400',
    ],
    category_id:    'fashion',
    category_name:  'Fashion',
    brand:          'Adidas',
    rating:         4.5,
    review_count:   2800,
    stock:          32,
    tags:           ['shoes', 'adidas', 'ultraboost', 'running'],
    is_featured:    false,
    is_new:         true,
    is_active:      true,
    created_at:     admin.firestore.Timestamp.now(),
  },
  {
    name:           'Levi\'s 501 Original Jeans',
    description:    'The original jean since 1873. Straight fit with a button fly, sits at the waist, and is made from 100% cotton denim that gets better with every wear.',
    price:          349,
    discount_price: null,
    images:         [
      'https://picsum.photos/seed/levis501/400/400',
      'https://picsum.photos/seed/levis501b/400/400',
    ],
    category_id:    'fashion',
    category_name:  'Fashion',
    brand:          'Levi\'s',
    rating:         4.4,
    review_count:   5100,
    stock:          60,
    tags:           ['jeans', 'levis', 'denim', 'pants'],
    is_featured:    false,
    is_new:         false,
    is_active:      true,
    created_at:     admin.firestore.Timestamp.now(),
  },
  {
    name:           'Ray-Ban Aviator Classic',
    description:    'A timeless design since 1937. The iconic pilot-style frame in gold with crystal green lenses that offer 100% UV protection. Perfect for any occasion.',
    price:          699,
    discount_price: 599,
    images:         [
      'https://picsum.photos/seed/rayban/400/400',
      'https://picsum.photos/seed/raybanb/400/400',
    ],
    category_id:    'fashion',
    category_name:  'Fashion',
    brand:          'Ray-Ban',
    rating:         4.7,
    review_count:   4300,
    stock:          40,
    tags:           ['sunglasses', 'rayban', 'aviator', 'accessories'],
    is_featured:    true,
    is_new:         false,
    is_active:      true,
    created_at:     admin.firestore.Timestamp.now(),
  },
  {
    name:           'Polo Ralph Lauren Shirt',
    description:    'Classic polo shirt crafted from soft cotton pique. Features signature embroidered Polo Pony at the chest, ribbed collar and cuffs, and two-button placket.',
    price:          299,
    discount_price: 249,
    images:         [
      'https://picsum.photos/seed/polo/400/400',
      'https://picsum.photos/seed/polob/400/400',
    ],
    category_id:    'fashion',
    category_name:  'Fashion',
    brand:          'Ralph Lauren',
    rating:         4.5,
    review_count:   2900,
    stock:          55,
    tags:           ['shirt', 'polo', 'ralphlauren', 'clothing'],
    is_featured:    false,
    is_new:         false,
    is_active:      true,
    created_at:     admin.firestore.Timestamp.now(),
  },
  {
    name:           'Gucci GG Canvas Tote Bag',
    description:    'Crafted from GG Supreme canvas with leather trim. Features double top handles, an internal zip pocket, and the iconic interlocking G motif throughout.',
    price:          3999,
    discount_price: null,
    images:         [
      'https://picsum.photos/seed/guccibag/400/400',
      'https://picsum.photos/seed/guccibagb/400/400',
    ],
    category_id:    'fashion',
    category_name:  'Fashion',
    brand:          'Gucci',
    rating:         4.8,
    review_count:   1200,
    stock:          12,
    tags:           ['bag', 'gucci', 'luxury', 'tote', 'accessories'],
    is_featured:    true,
    is_new:         false,
    is_active:      true,
    created_at:     admin.firestore.Timestamp.now(),
  },

  // ── Food (4 products) ─────────────────────────────────────────────────────
  {
    name:           'Nespresso Vertuo Coffee Machine',
    description:    'Brew the perfect cup every time with Centrifusion technology. Compatible with all Vertuo capsules for espresso, double espresso, gran lungo, mug, and alto.',
    price:          899,
    discount_price: 749,
    images:         [
      'https://picsum.photos/seed/nespresso/400/400',
      'https://picsum.photos/seed/nespressob/400/400',
    ],
    category_id:    'food',
    category_name:  'Food',
    brand:          'Nespresso',
    rating:         4.6,
    review_count:   3400,
    stock:          25,
    tags:           ['coffee', 'nespresso', 'machine', 'kitchen'],
    is_featured:    false,
    is_new:         false,
    is_active:      true,
    created_at:     admin.firestore.Timestamp.now(),
  },
  {
    name:           'KitchenAid Stand Mixer',
    description:    'The iconic stand mixer with 10 speeds and a 4.8L stainless steel bowl. Includes flat beater, dough hook, and wire whip. Tilt-head design for easy access.',
    price:          2499,
    discount_price: 1999,
    images:         [
      'https://picsum.photos/seed/kitchenaid/400/400',
      'https://picsum.photos/seed/kitchenaidb/400/400',
    ],
    category_id:    'food',
    category_name:  'Food',
    brand:          'KitchenAid',
    rating:         4.8,
    review_count:   6700,
    stock:          15,
    tags:           ['mixer', 'kitchenaid', 'baking', 'kitchen', 'cooking'],
    is_featured:    true,
    is_new:         false,
    is_active:      true,
    created_at:     admin.firestore.Timestamp.now(),
  },
  {
    name:           'Vitamix E310 Blender',
    description:    'Professional-grade blender with aircraft-grade stainless steel blades that can blend through the toughest ingredients. Variable speed control and pulse feature.',
    price:          1799,
    discount_price: 1499,
    images:         [
      'https://picsum.photos/seed/vitamix/400/400',
      'https://picsum.photos/seed/vitamixb/400/400',
    ],
    category_id:    'food',
    category_name:  'Food',
    brand:          'Vitamix',
    rating:         4.7,
    review_count:   4200,
    stock:          20,
    tags:           ['blender', 'vitamix', 'smoothie', 'kitchen'],
    is_featured:    false,
    is_new:         true,
    is_active:      true,
    created_at:     admin.firestore.Timestamp.now(),
  },
  {
    name:           'Instant Pot Duo 7-in-1',
    description:    '7-in-1 multi-cooker: pressure cooker, slow cooker, rice cooker, steamer, sauté, yogurt maker, and food warmer. 6 quart capacity, 13 one-touch programs.',
    price:          499,
    discount_price: 399,
    images:         [
      'https://picsum.photos/seed/instantpot/400/400',
      'https://picsum.photos/seed/instantpotb/400/400',
    ],
    category_id:    'food',
    category_name:  'Food',
    brand:          'Instant Pot',
    rating:         4.7,
    review_count:   8900,
    stock:          40,
    tags:           ['cooker', 'instantpot', 'pressure', 'kitchen'],
    is_featured:    false,
    is_new:         false,
    is_active:      true,
    created_at:     admin.firestore.Timestamp.now(),
  },

  // ── Home (4 products) ─────────────────────────────────────────────────────
  {
    name:           'Dyson V15 Detect Vacuum',
    description:    'The most powerful, intelligent cordless vacuum. Laser reveals hidden dust on floors. HEPA filtration captures 99.99% of particles as small as 0.3 microns.',
    price:          2799,
    discount_price: null,
    images:         [
      'https://picsum.photos/seed/dysonv15/400/400',
      'https://picsum.photos/seed/dysonv15b/400/400',
    ],
    category_id:    'home',
    category_name:  'Home',
    brand:          'Dyson',
    rating:         4.7,
    review_count:   1800,
    stock:          12,
    tags:           ['vacuum', 'dyson', 'cordless', 'cleaning'],
    is_featured:    true,
    is_new:         false,
    is_active:      true,
    created_at:     admin.firestore.Timestamp.now(),
  },
  {
    name:           'Philips Hue Starter Kit',
    description:    'Transform your home with smart lighting. Includes 3 White & Color Ambiance bulbs and Hue Bridge. 16 million colors and whites, voice and app controlled.',
    price:          599,
    discount_price: 499,
    images:         [
      'https://picsum.photos/seed/philipshue/400/400',
      'https://picsum.photos/seed/philipshueb/400/400',
    ],
    category_id:    'home',
    category_name:  'Home',
    brand:          'Philips',
    rating:         4.5,
    review_count:   3200,
    stock:          30,
    tags:           ['smart', 'lighting', 'philips', 'hue', 'home'],
    is_featured:    false,
    is_new:         false,
    is_active:      true,
    created_at:     admin.firestore.Timestamp.now(),
  },
  {
    name:           'IKEA MALM King Bed Frame',
    description:    'Clean-lined bed frame in a timeless design. Made of solid wood and board, suitable for slatted bed bases. High-gloss white finish with smooth surfaces.',
    price:          1299,
    discount_price: 999,
    images:         [
      'https://picsum.photos/seed/ikeabed/400/400',
      'https://picsum.photos/seed/ikeabedb/400/400',
    ],
    category_id:    'home',
    category_name:  'Home',
    brand:          'IKEA',
    rating:         4.3,
    review_count:   2100,
    stock:          8,
    tags:           ['bed', 'ikea', 'furniture', 'bedroom'],
    is_featured:    false,
    is_new:         false,
    is_active:      true,
    created_at:     admin.firestore.Timestamp.now(),
  },
  {
    name:           'Nespresso Aeroccino Milk Frother',
    description:    'Create hot or cold milk froth in under 60 seconds. Perfect for cappuccinos, lattes, and macchiatos. Easy to clean with non-stick coating inside.',
    price:          249,
    discount_price: 199,
    images:         [
      'https://picsum.photos/seed/aeroccino/400/400',
      'https://picsum.photos/seed/aeroccinob/400/400',
    ],
    category_id:    'home',
    category_name:  'Home',
    brand:          'Nespresso',
    rating:         4.6,
    review_count:   4500,
    stock:          50,
    tags:           ['frother', 'milk', 'coffee', 'kitchen', 'nespresso'],
    is_featured:    false,
    is_new:         true,
    is_active:      true,
    created_at:     admin.firestore.Timestamp.now(),
  },

  // ── Sports (4 products) ───────────────────────────────────────────────────
  {
    name:           'Garmin Forerunner 265 Watch',
    description:    'Running smartwatch with AMOLED display, training readiness, and daily suggested workouts. Built-in GPS, heart rate, and advanced running dynamics.',
    price:          1899,
    discount_price: 1699,
    images:         [
      'https://picsum.photos/seed/garmin/400/400',
      'https://picsum.photos/seed/garminb/400/400',
    ],
    category_id:    'sports',
    category_name:  'Sports',
    brand:          'Garmin',
    rating:         4.7,
    review_count:   1400,
    stock:          22,
    tags:           ['watch', 'garmin', 'running', 'fitness', 'gps'],
    is_featured:    true,
    is_new:         true,
    is_active:      true,
    created_at:     admin.firestore.Timestamp.now(),
  },
  {
    name:           'Bowflex SelectTech 552 Dumbbells',
    description:    'Adjustable dumbbells replace 15 sets of weights. Dial system selects from 2.5 to 52.5 lbs in 2.5 lb increments. Space-efficient design for home gym.',
    price:          2299,
    discount_price: 1999,
    images:         [
      'https://picsum.photos/seed/bowflex/400/400',
      'https://picsum.photos/seed/bowflexb/400/400',
    ],
    category_id:    'sports',
    category_name:  'Sports',
    brand:          'Bowflex',
    rating:         4.8,
    review_count:   5600,
    stock:          10,
    tags:           ['dumbbells', 'bowflex', 'gym', 'fitness', 'weights'],
    is_featured:    true,
    is_new:         false,
    is_active:      true,
    created_at:     admin.firestore.Timestamp.now(),
  },
  {
    name:           'Peloton Yoga Mat',
    description:    'High-density non-slip yoga mat with alignment lines. 6mm thick for superior cushioning. Made from eco-friendly TPE material, moisture resistant and easy to clean.',
    price:          199,
    discount_price: 159,
    images:         [
      'https://picsum.photos/seed/yogamat/400/400',
      'https://picsum.photos/seed/yogamatb/400/400',
    ],
    category_id:    'sports',
    category_name:  'Sports',
    brand:          'Peloton',
    rating:         4.4,
    review_count:   2300,
    stock:          70,
    tags:           ['yoga', 'mat', 'fitness', 'exercise', 'peloton'],
    is_featured:    false,
    is_new:         false,
    is_active:      true,
    created_at:     admin.firestore.Timestamp.now(),
  },
  {
    name:           'Wilson Pro Staff Tennis Racket',
    description:    'Used by Roger Federer for over 20 years. Braided graphite construction for exceptional feel. 97 sq in head size, 340g weight, perfect for advanced players.',
    price:          899,
    discount_price: null,
    images:         [
      'https://picsum.photos/seed/wilson/400/400',
      'https://picsum.photos/seed/wilsonb/400/400',
    ],
    category_id:    'sports',
    category_name:  'Sports',
    brand:          'Wilson',
    rating:         4.8,
    review_count:   980,
    stock:          18,
    tags:           ['tennis', 'wilson', 'racket', 'sport'],
    is_featured:    false,
    is_new:         false,
    is_active:      true,
    created_at:     admin.firestore.Timestamp.now(),
  },

  // ── Beauty (4 products) ───────────────────────────────────────────────────
  {
    name:           'Dyson Airwrap Multi-Styler',
    description:    'Styles and dries simultaneously with no extreme heat. Uses air to curl, wave, smooth, and dry. Includes multiple attachments for different hair types and styles.',
    price:          2199,
    discount_price: 1999,
    images:         [
      'https://picsum.photos/seed/dysonair/400/400',
      'https://picsum.photos/seed/dysonairb/400/400',
    ],
    category_id:    'beauty',
    category_name:  'Beauty',
    brand:          'Dyson',
    rating:         4.7,
    review_count:   3400,
    stock:          20,
    tags:           ['hair', 'dyson', 'styler', 'beauty', 'hairdryer'],
    is_featured:    true,
    is_new:         false,
    is_active:      true,
    created_at:     admin.firestore.Timestamp.now(),
  },
  {
    name:           'La Mer Moisturizing Cream 60ml',
    description:    'The legendary moisturizer powered by Miracle Broth. Helps heal dryness, reduce the look of fine lines, and restore radiance. Suitable for all skin types.',
    price:          1299,
    discount_price: null,
    images:         [
      'https://picsum.photos/seed/lamer/400/400',
      'https://picsum.photos/seed/lamerb/400/400',
    ],
    category_id:    'beauty',
    category_name:  'Beauty',
    brand:          'La Mer',
    rating:         4.6,
    review_count:   2100,
    stock:          25,
    tags:           ['skincare', 'lamer', 'cream', 'moisturizer', 'luxury'],
    is_featured:    false,
    is_new:         false,
    is_active:      true,
    created_at:     admin.firestore.Timestamp.now(),
  },
  {
    name:           'Charlotte Tilbury Magic Cream',
    description:    'The world-famous moisturiser that gives your skin a super-natural, lit-from-within glow. Lightweight formula with hyaluronic acid, peptides, and vitamin C.',
    price:          449,
    discount_price: 399,
    images:         [
      'https://picsum.photos/seed/ctilbury/400/400',
      'https://picsum.photos/seed/ctilburyb/400/400',
    ],
    category_id:    'beauty',
    category_name:  'Beauty',
    brand:          'Charlotte Tilbury',
    rating:         4.8,
    review_count:   4800,
    stock:          35,
    tags:           ['skincare', 'cream', 'charlotte', 'beauty', 'glow'],
    is_featured:    true,
    is_new:         true,
    is_active:      true,
    created_at:     admin.firestore.Timestamp.now(),
  },
  {
    name:           'Fenty Beauty Foundation',
    description:    'Soft matte longwear foundation with SPF 15. Available in 50 shades for all skin tones. Provides medium-to-full buildable coverage that lasts up to 24 hours.',
    price:          199,
    discount_price: null,
    images:         [
      'https://picsum.photos/seed/fenty/400/400',
      'https://picsum.photos/seed/fentyb/400/400',
    ],
    category_id:    'beauty',
    category_name:  'Beauty',
    brand:          'Fenty Beauty',
    rating:         4.7,
    review_count:   6200,
    stock:          80,
    tags:           ['makeup', 'foundation', 'fenty', 'beauty', 'cosmetics'],
    is_featured:    false,
    is_new:         true,
    is_active:      true,
    created_at:     admin.firestore.Timestamp.now(),
  },
];

// ── Banners ───────────────────────────────────────────────────────────────────
const banners = [
  {
    title:     'Flash Sale Today!',
    subtitle:  'Up to 50% off on electronics',
    image_url: 'https://picsum.photos/seed/banner1/800/400',
    action:    'electronics',
    is_active: true,
    order:     1,
  },
  {
    title:     'Free Delivery',
    subtitle:  'On all orders above SAR 200',
    image_url: 'https://picsum.photos/seed/banner2/800/400',
    action:    null,
    is_active: true,
    order:     2,
  },
  {
    title:     'New Arrivals',
    subtitle:  'Explore the latest collections',
    image_url: 'https://picsum.photos/seed/banner3/800/400',
    action:    'fashion',
    is_active: true,
    order:     3,
  },
];

// ── Seed function ─────────────────────────────────────────────────────────────
async function seed() {
  console.log('🌱 Starting Firestore seed...\n');

  // ── Categories ─────────────────────────────────────────────────────────────
  console.log('📁 Seeding categories...');
  for (const cat of categories) {
    await db.collection('categories').doc(cat.id).set(cat);
    console.log(`   ✅ ${cat.name}`);
  }

  // ── Products ───────────────────────────────────────────────────────────────
  console.log('\n📦 Seeding products...');
  for (const prod of products) {
    await db.collection('products').add(prod);
    console.log(`   ✅ ${prod.name}`);
  }

  // ── Banners ────────────────────────────────────────────────────────────────
  console.log('\n🖼️  Seeding banners...');
  for (const banner of banners) {
    await db.collection('banners').add(banner);
    console.log(`   ✅ ${banner.title}`);
  }

  console.log('\n🎉 Done! Seeded:');
  console.log(`   • ${categories.length} categories`);
  console.log(`   • ${products.length} products`);
  console.log(`   • ${banners.length} banners`);

  process.exit(0);
}

seed().catch(err => {
  console.error('\n❌ Seed failed:', err);
  process.exit(1);
});